; PlatformIO Project Configuration File for HonDASH LVGL (ESP32)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    lvgl/lvgl@^8.3.11
    bodmer/TFT_eSPI@^2.5.43

build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_MISO=19
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=4
    -D TOUCH_CS=21
    -D SPI_FREQUENCY=40000000
    -D SPI_TOUCH_FREQUENCY=2500000
    -I lvgl
    -D LV_CONF_INCLUDE_SIMPLE

[env:esp32s3-cyd]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -I lvgl
lib_deps =
    lvgl/lvgl@^8.3.11
    bodmer/TFT_eSPI@^2.5.43
